server:
  address: 0.0.0.0
  # 포트 번호
  port: 8080 
  servlet:
    # 서블릿 통신 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  devtools:
    # 정적 소스(classpath) 파일 변경 시 자동 브라우저 재실행
    livereload:
      enabled: true
    # 서버 측 파일이 변경되면 재실행 안함(false)
    restart:
      enabled: true
  # 객체를 json으로 변환하는 과정을 serialize이라 하고, 변환할 때 객체를 못가져와도 변환에 실패하지 않는다는 뜻
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: hoosshop
    password: 1234
  jpa:
    database: oracle
    show-sql: false
    hibernate:
      ddl-auto: update
      # create : 기존 테이블 삭제 후 다시 생성
      # create-drop : 테이블을 생성한다. 종료 시점에 생성한 테이블읈 삭제한다.
      # update : 변경된 것만 반영 한다.
      # validate : 엔티티와 테이블이 정상 매핑되었는지 확인
      # none : 사용하지 않는다.
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  
imp:
  key: 7636838104380604
  secret: zA9EFSADZUeepgzyesZqCOZr2sO2h5eD8xC4fwhzqnGrQyhHbmQrD9HYrVuCHALeiKKoekFkWl10hgAQ